version: '2'
services:
    awesome_jhipster4_demo-app:
        image: awesome_jhipster4_demo
        external_links:
            - awesome_jhipster4_demo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/awesome_jhipster4_demo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    awesome_jhipster4_demo-postgresql:
        extends:
            file: postgresql.yml
            service: awesome_jhipster4_demo-postgresql
